### ISSUE TITLE
./pcheck.sh: ligne 154 : printf: 5.00000000000000000000:

### ISSUE THREAD

**Issue by FabienZa** [The-SamminAter/product-checker#1]
Hello,

Thanks to your work.

I have a tiny error : 
```bash
~/product-checker$ ./pcheck.sh 
[!] Notice: check started
./pcheck.sh: ligne 154 : printf: 5.00000000000000000000: nombre non valable
[!] Notice: check completed - 5,00 minutes until the next one
```

To fix I removed the option `-l` at line 154 :  
```bash
	else
		print "notice" "check completed - "$(printf %.2f $(echo "${delay}/60" | bc))" minutes until the next one" #Prints the calculation (of minutes) with rounding to two decimal places
	fi
```

**Comment by The-SamminAter** [comment]
The decimals are intended, the issue seems to be your `printf`, which should accept `5.00000000000000000000` just fine

**Comment by FabienZa** [comment]
Ok, I checked, it's a problem with my locale.
I need to add `export LC_NUMERIC=C` in the script to don't have this error.
May be it's possible to add it permanently ?
